name: Pulumi-App
on:
  push:
    tags:
      - '*'
jobs:
  demo-hello-python-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pulumi-App is at version ${{ steps.tagkit.outputs.tag }}"
      - uses: actions/checkout@v2
      - name: build
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REPO: rbroker/pulumi-app
          GET_LOCAL: "N"
        run: ./ci.sh